version: 2.1
commands:
  gcloud_config:
    steps:
      - run:
          name: Gcloud Config
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: GCloud Auth configure-docker
          command: |
            gcloud auth configure-docker --quiet --project ${GOOGLE_PROJECT_ID}
jobs:
  create_image:
    docker:
      - image: google/cloud-sdk
    steps:
      - gcloud_config
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Build
          command: |
            docker build . -t gcr.io/${GOOGLE_PROJECT_ID}/frontend-sports:${CIRCLE_SHA1}
      - run:
          name: Docker Push
          command: |
            docker push gcr.io/${GOOGLE_PROJECT_ID}/frontend-sports:${CIRCLE_SHA1}
  build_pull_request:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: install ruby
          command: |
            apt-get -y install ruby
      - gcloud_config
      - run:
          name: git clone
          command: |
            mkdir ~/.ssh/
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            git clone https://${GITHUB_API_TOKEN}:x-oauth-basic@github.com/tsuayumu/infra_sports.git
      - run:
          name: git config
          command: |
            git config --global user.email "t.ayu.1605@gmail.com"
            git config --global user.name "tsuayumu"
      - run:
          name: build pull request
          working_directory: ~/project/infra_sports
          command: |
            ruby bin/newest_manifest
            ruby bin/build_pull_request
workflows:
  build:
    jobs:
      - create_image:
          filters:
            branches:
              only: master
      - build_pull_request:
          filters:
            branches:
              only: master
          requires:
            - create_image
