version: 2.1
jobs:
  create_image:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Gcloud Config
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: GCloud Auth configure-docker
          command: |
            gcloud auth configure-docker --quiet --project ${GOOGLE_PROJECT_ID}
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Build
          command: |
            docker build . -t gcr.io/${GOOGLE_PROJECT_ID}/frontend_sports:${CIRCLE_SHA1}
      - run:
          name: Docker Push
          command: |
            docker push gcr.io/${GOOGLE_PROJECT_ID}/frontend_sports:${CIRCLE_SHA1}
workflows:
  build:
    jobs:
      - create_image:
          filters:
            branches:
              only: master
